dest_server: https://kubernetes.default.svc

environment: default

app_example:
  enabled: true

aws_csi_driver:
  enabled: true

confluent_operator:
  enabled: true

confluent_components:
  enabled: false

self_service_kafka:
  enabled: false

external_dns:
  enabled: false

serviceAccounts:
  enabled: true